[build]
  command = "npm --prefix build-frontend-foundation ci && npm --prefix build-frontend-foundation run build"
  publish = "build-frontend-foundation/out"

[build.environment]
  NODE_VERSION = "22"