import EditorialPage from "@/components/EditorialPage";
export const metadata = { title: "Privacy & terms | MangaMarketplace" };
export default function PrivacyTermsPage() { return <EditorialPage eyebrow="Privacy & marketplace terms" title="Plain-language expectations for a verified community marketplace." intro="This pre-launch summary explains how the product is designed to handle accounts, listings, inspection-controlled seller payments, and community conduct. It is not a substitute for launch-ready legal terms reviewed for every operating jurisdiction." note="Last product revision: September 7, 2026. Do not accept live payments until payments counsel and Stripe underwriting approve the exact funds flow, goods, states, payout timing, and customer agreements." sections={[
  { number: "01", title: "Information the service uses", body: "Account details, saved addresses, listing content, seller images, session data, and transaction references support core marketplace functions. Payment card data is entered on Stripe-hosted Checkout and is not stored by MangaMarketplace." },
  { number: "02", title: "Marketplace responsibilities", body: "Sellers must accurately describe items they own and can ship. Buyers must provide usable contact and delivery information. Fraud, counterfeit goods, harassment, and manipulation of marketplace systems are prohibited." },
  { number: "03", title: "Inspection-controlled seller payment", body: "Buyer payment is captured on the marketplace Stripe account. The seller’s net proceeds are not transferred until the item passes physical verification and the outbound carrier handoff is recorded. This workflow is not advertised as legal escrow, and Stripe is not an escrow provider." },
  { number: "04", title: "Failed verification, refunds, and disputes", body: "An item that fails verification enters a full refund workflow to the original payment method before any seller transfer. Verification does not remove cardholder dispute rights; unauthorized-payment, nondelivery, and not-as-described claims can arise after shipment or seller payment." },
  { number: "05", title: "Records, privacy, and contact", body: "Transaction, inspection, shipment, refund, and payment-event records are restricted and retained for fraud, accounting, dispute, and legal obligations. Accounts with transaction history use a reviewed deactivation or anonymization process rather than destructive self-deletion. Retention periods, governing law, age requirements, tax terms, and regional notices must be finalized before production." },
]} cta={{ label: "Contact the team", href: "/contact", text: "Ask a policy or privacy question." }} />; }
