import Link from "next/link";
import Footer from "@/components/Footer";
import styles from "./community.module.css";
export const metadata = { title: "Community | MangaMarketplace" };
const shelves = [{ name: "Small press discoveries", owner: "paper.moon", count: 18, tag: "Indie" }, { name: "Urasawa reading order", owner: "panelby-panel", count: 27, tag: "Mystery" }, { name: "First-volume gateway shelf", owner: "shelfstarter", count: 34, tag: "Starter sets" }];
export default function CommunityPage() { return <><main className={styles.main} id="main-content">
  <header className={styles.hero}><p>Community commons</p><h1>Collections are better when they start conversations.</h1><div><p>Follow the shelves, reading lists, and collector notes that make the hunt more human.</p><Link href="/account/signup">Join the community <span aria-hidden="true">→</span></Link></div></header>
  <section className={styles.pulse} aria-label="Community pulse"><div><strong>2.4k</strong><span>volumes cataloged</span></div><div><strong>186</strong><span>open shelf lists</span></div><div><strong>41</strong><span>series circles</span></div><p>Preview community data</p></section>
  <section className={styles.shelves}><div className={styles.heading}><div><p>Public shelves</p><h2>Worth pulling up a chair for</h2></div><Link href="/series">Explore by series</Link></div><div className={styles.cards}>{shelves.map((shelf, index) => <article key={shelf.name}><div className={styles.spines} aria-hidden="true">{Array.from({ length: 6 }, (_, i) => <i key={i} style={{ blockSize: `${54 + ((i + index) % 3) * 16}%` }} />)}</div><p>{shelf.tag}</p><h3>{shelf.name}</h3><dl><div><dt>Curated by</dt><dd>@{shelf.owner}</dd></div><div><dt>Volumes</dt><dd>{shelf.count}</dd></div></dl><Link href={`/search?q=${encodeURIComponent(shelf.tag)}`}>Browse related listings <span aria-hidden="true">↗</span></Link></article>)}</div></section>
  <section className={styles.rules}><p>Good shelf citizenship</p><div><h2>Share the detail. Respect the reader.</h2><ul><li><span>01</span><strong>Describe, don’t exaggerate</strong><p>Specific condition notes help the next collector decide.</p></li><li><span>02</span><strong>Credit recommendations</strong><p>Say where a reading order or discovery came from.</p></li><li><span>03</span><strong>Keep spoilers labeled</strong><p>Let new readers choose how much they want to know.</p></li></ul></div></section>
  </main><Footer /></>; }
