import { DeepPartial } from "typeorm";

import { CatalogProduct } from "../../catalog-products/entities/catalog-product.entity";
import { PRODUCT_IDS } from "./seed-identifiers";

export const catalogProductSeeds: DeepPartial<CatalogProduct>[] = [
  {
    productId: PRODUCT_IDS.onePieceVolume1,
    title: "One Piece, Vol. 1",
    series: "One Piece",
    volumeNumber: 1,
    edition: "Paperback",
    isbn: "9781569319017",
    author: "Eiichiro Oda",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2003-06-01"),
  },
  {
    productId: PRODUCT_IDS.narutoVolume1,
    title: "Naruto, Vol. 1",
    series: "Naruto",
    volumeNumber: 1,
    edition: "Paperback",
    isbn: "9781569319000",
    author: "Masashi Kishimoto",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2003-08-06"),
  },
  {
    productId: PRODUCT_IDS.deathNoteBlackEdition1,
    title: "Death Note Black Edition, Vol. 1",
    series: "Death Note",
    volumeNumber: 1,
    edition: "Black Edition",
    isbn: "9781421539645",
    author: "Tsugumi Ohba and Takeshi Obata",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2010-12-28"),
  },
  {
    productId: PRODUCT_IDS.berserkDeluxe1,
    title: "Berserk Deluxe Volume 1",
    series: "Berserk",
    volumeNumber: 1,
    edition: "Deluxe Hardcover",
    isbn: "9781506711980",
    author: "Kentaro Miura",
    publisher: "Dark Horse Manga",
    language: "en",
    publicationDate: new Date("2019-03-26"),
  },
  {
    productId: PRODUCT_IDS.spyFamilyVolume1,
    title: "Spy x Family, Vol. 1",
    series: "Spy x Family",
    volumeNumber: 1,
    edition: "Paperback",
    isbn: "9781974715466",
    author: "Tatsuya Endo",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2020-06-02"),
  },
  {
    productId: PRODUCT_IDS.chainsawManVolume1,
    title: "Chainsaw Man, Vol. 1",
    series: "Chainsaw Man",
    volumeNumber: 1,
    edition: "Paperback",
    isbn: "9781974709939",
    author: "Tatsuki Fujimoto",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2020-10-06"),
  },
  {
    productId: PRODUCT_IDS.fullmetalEdition1,
    title: "Fullmetal Alchemist: Fullmetal Edition, Vol. 1",
    series: "Fullmetal Alchemist",
    volumeNumber: 1,
    edition: "Fullmetal Edition Hardcover",
    isbn: "9781421599805",
    author: "Hiromu Arakawa",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2018-05-08"),
  },
  {
    productId: PRODUCT_IDS.demonSlayerVolume1,
    title: "Demon Slayer: Kimetsu no Yaiba, Vol. 1",
    series: "Demon Slayer: Kimetsu no Yaiba",
    volumeNumber: 1,
    edition: "Paperback",
    isbn: "9781974700523",
    author: "Koyoharu Gotouge",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2018-07-03"),
  },
  {
    productId: PRODUCT_IDS.vagabondVizbig1,
    title: "Vagabond VIZBIG Edition, Vol. 1",
    series: "Vagabond",
    volumeNumber: 1,
    edition: "VIZBIG Edition",
    isbn: "9781421520544",
    author: "Takehiko Inoue",
    publisher: "VIZ Media",
    language: "en",
    publicationDate: new Date("2008-09-16"),
  },
];
