import { DeepPartial } from "typeorm";

import {
  InventoryAvailability,
  InventoryItem,
} from "../../inventory-items/entities/inventory-item.entity";
import {
  INVENTORY_ITEM_IDS,
  PRODUCT_IDS,
  SELLER_IDS,
} from "./seed-identifiers";

export const inventoryItemSeeds: DeepPartial<InventoryItem>[] = [
  {
    itemId: INVENTORY_ITEM_IDS.collectorOnePiece,
    productId: PRODUCT_IDS.onePieceVolume1,
    ownerId: SELLER_IDS.collector,
    condition: "Very Good",
    conditionNotes: "Light shelf wear; pages are clean and unmarked.",
    availability: InventoryAvailability.LISTED,
    acquisitionPrice: "7.00",
    sellerPhotoPath: "/seed-images/one-piece-vol-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.collectorNaruto,
    productId: PRODUCT_IDS.narutoVolume1,
    ownerId: SELLER_IDS.collector,
    condition: "Like New",
    conditionNotes: "Read once and stored in a smoke-free home.",
    availability: InventoryAvailability.AVAILABLE,
    acquisitionPrice: "6.50",
    sellerPhotoPath: "/seed-images/naruto-vol-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.collectorDeathNote,
    productId: PRODUCT_IDS.deathNoteBlackEdition1,
    ownerId: SELLER_IDS.collector,
    condition: "Good",
    conditionNotes: "Minor scuffing on the black cover.",
    availability: InventoryAvailability.SOLD,
    acquisitionPrice: "12.00",
    sellerPhotoPath: "/seed-images/death-note-black-edition-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.collectorBerserk,
    productId: PRODUCT_IDS.berserkDeluxe1,
    ownerId: SELLER_IDS.collector,
    condition: "Like New",
    conditionNotes: "Dust-free with sharp corners and an intact ribbon.",
    availability: InventoryAvailability.LISTED,
    acquisitionPrice: "30.00",
    sellerPhotoPath: "/seed-images/berserk-deluxe-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.traderSpyFamily,
    productId: PRODUCT_IDS.spyFamilyVolume1,
    ownerId: SELLER_IDS.trader,
    condition: "Very Good",
    conditionNotes: "Small crease on the rear cover.",
    availability: InventoryAvailability.LISTED,
    acquisitionPrice: "5.00",
    sellerPhotoPath: "/seed-images/spy-family-vol-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.traderChainsawMan,
    productId: PRODUCT_IDS.chainsawManVolume1,
    ownerId: SELLER_IDS.trader,
    condition: "Fair",
    conditionNotes: "Reading copy with visible spine wear.",
    availability: InventoryAvailability.UNAVAILABLE,
    acquisitionPrice: "4.00",
    sellerPhotoPath: null,
  },
  {
    itemId: INVENTORY_ITEM_IDS.traderFullmetal,
    productId: PRODUCT_IDS.fullmetalEdition1,
    ownerId: SELLER_IDS.trader,
    condition: "New",
    conditionNotes: "Still sealed in the publisher wrap.",
    availability: InventoryAvailability.AVAILABLE,
    acquisitionPrice: "14.50",
    sellerPhotoPath: "/seed-images/fullmetal-edition-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.traderDemonSlayer,
    productId: PRODUCT_IDS.demonSlayerVolume1,
    ownerId: SELLER_IDS.trader,
    condition: "Good",
    conditionNotes: "Clean interior with light edge wear.",
    availability: InventoryAvailability.LISTED,
    acquisitionPrice: "5.50",
    sellerPhotoPath: "/seed-images/demon-slayer-vol-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.readerVagabond,
    productId: PRODUCT_IDS.vagabondVizbig1,
    ownerId: SELLER_IDS.reader,
    condition: "Very Good",
    conditionNotes: null,
    availability: InventoryAvailability.AVAILABLE,
    acquisitionPrice: "13.00",
    sellerPhotoPath: "/seed-images/vagabond-vizbig-1.jpg",
  },
  {
    itemId: INVENTORY_ITEM_IDS.readerOnePiece,
    productId: PRODUCT_IDS.onePieceVolume1,
    ownerId: SELLER_IDS.reader,
    condition: "Good",
    conditionNotes: "Older printing with mild page yellowing.",
    availability: InventoryAvailability.AVAILABLE,
    acquisitionPrice: null,
    sellerPhotoPath: null,
  },
];
